const translations = {
    it: {
        hero_title: '"Vediamo dove perdiamo tempo e soldi"',
        hero_subtitle: 'Supporto ad aziende di produzione per ottimizzare impianti esistenti e valorizzare la diagnostica senior.',
        btn_discover: 'Scopri i Servizi',
        section_industrial_title: 'Ottimizzazione e Affidabilità Impianti',
        section_industrial_subtitle: 'Non tecnologia pura, ma visione sistemica e capacità diagnostica.',
        card_guasti_title: 'Risoluzione Guasti',
        card_guasti_desc: 'Interventi mirati per risolvere guasti ripetitivi e impedire che i problemi si ripresentino.',
        card_fermi_title: 'Riduzione Fermi Macchina',
        card_fermi_desc: 'Analisi logica dei processi per minimizzare le inefficienze croniche e i tempi morti.',
        card_rendimento_title: 'Miglioramento Rendimento',
        card_rendimento_desc: 'Ottimizzazione delle performance produttive attraverso un approccio analitico e globale.',
        card_modern_title: 'Supporto Modernizzazione',
        card_modern_desc: "Supporto tecnico professionale per il rinnovamento e l'ammodernamento dei macchinari esistenti.",
        card_invest_title: 'Valutazione Pre-Investimento',
        card_invest_desc: 'Analisi tecnica e consulenza per garantire che ogni nuovo investimento sia mirato ed efficace.',
        card_logica_title: 'Analisi Logica',
        card_logica_desc: 'Studio approfondito dei flussi di lavoro per eliminare colli di bottiglia e sprechi.',
        quote: '"Un tecnico senior vale più di uno che sa scrivere codice nuovo."',
        quote_desc: "La nostra forza risiede nell'esperienza e nella capacità di vedere l'intero impianto, non solo il singolo componente.",
        nav_tech: 'Tecnologia',
        nav_wellness: 'Benessere',
        nav_industrial: 'Industria',
        tech_title: 'Soluzioni Tecnologiche',
        tech_subtitle: 'Dall\'automazione industriale allo sviluppo di App Android e siti web moderni.',
        wellness_title: 'Reiki & Benessere',
        wellness_subtitle: 'Soluzioni per l\'equilibrio della persona e il recupero delle energie.',
        footer_rights: 'Tutti i diritti riservati.',
        nav_app: 'App Instruments',
        inst_hero_title: 'Instruments Tools',
        inst_hero_subtitle: 'Tutto in uno: strumenti per ingegneria, calcoli tecnici, conversioni e toolkit professionale.',
        inst_desc: 'Instruments è il toolkit definitivo progettato per ingegneri, tecnici e hobbisti che necessitano di calcoli precisi e immediati direttamente sul proprio dispositivo Android. Perfetta per professionisti dell\'automazione, elettrotecnici e idraulici, l\'app offre una suite completa di strumenti pronti all\'uso:',
        inst_feat1_title: 'Calcoli Elettrici Professionali',
        inst_feat1_desc: 'Calcolo delle linee elettriche, dimensionamento cavi e caduta di tensione.',
        inst_feat2_title: 'Strumentazione e Segnali',
        inst_feat2_desc: 'Convertitore di segnali 4-20mA con visualizzazione della scala.',
        inst_feat3_title: 'Calcolatore Piping',
        inst_feat3_desc: 'Dimensionamento tubazioni e calcoli idraulici per fluidi.',
        inst_feat4_title: 'Codice Colori Resistenze',
        inst_feat4_desc: 'Identifica il valore delle resistenze a 4 o 5 bande in un istante.',
        inst_feat5_title: 'Convertitori di Unità',
        inst_feat5_desc: 'Potenza, Pressione, Temperatura, Valuta in tempo reale.',
        inst_why_title: 'Perché scegliere Instruments?',
        inst_why1: 'Semplice e intuitiva: Interfaccia pulita in Material Design 3.',
        inst_why2: 'Multilingua: Supporto completo per Italiano, Inglese e Tedesco.',
        inst_why3: 'Precisione Tecnica: Algoritmi testati per uso professionale.',
        inst_download: 'Scarica Instruments oggi stesso e trasforma il tuo smartphone in un laboratorio di calcolo portatile!',
        inst_btn_play: 'Scarica su Google Play',
        inst_nav_home: 'Torna alla Home',
        footer_visits: 'Visite:'
    },
    en: {
        hero_title: '"Let\'s see where we are losing time and money"',
        hero_subtitle: 'Support for production companies to optimize existing plants and enhance senior diagnostics.',
        btn_discover: 'Discover Services',
        section_industrial_title: 'Plant Optimization & Reliability',
        section_industrial_subtitle: 'Not pure technology, but systemic vision and diagnostic capability.',
        card_guasti_title: 'Fault Resolution',
        card_guasti_desc: 'Targeted interventions to resolve repetitive faults and prevent problems from recurring.',
        card_fermi_title: 'Downtime Reduction',
        card_fermi_desc: 'Logical analysis of processes to minimize chronic inefficiencies and idle time.',
        card_rendimento_title: 'Yield Improvement',
        card_rendimento_desc: 'Optimization of production performance through an analytical and global approach.',
        card_modern_title: 'Modernization Support',
        card_modern_desc: 'Professional technical support for the renewal and modernization of existing machinery.',
        card_invest_title: 'Pre-Investment Evaluation',
        card_invest_desc: 'Technical analysis and consultancy to ensure every new investment is targeted and effective.',
        card_logica_title: 'Logical Analysis',
        card_logica_desc: 'In-depth study of workflows to eliminate bottlenecks and waste.',
        quote: '"A senior technician is worth more than someone who just writes new code."',
        quote_desc: 'Our strength lies in experience and the ability to see the entire plant, not just the single component.',
        nav_tech: 'Technology',
        nav_wellness: 'Wellness',
        nav_industrial: 'Industry',
        tech_title: 'Technology Solutions',
        tech_subtitle: 'From industrial automation to modern Android App and website development.',
        wellness_title: 'Reiki & Wellness',
        wellness_subtitle: 'Solutions for human balance and energy recovery.',
        footer_rights: 'All rights reserved.',
        nav_app: 'Instruments App',
        inst_hero_title: 'Instruments Tools',
        inst_hero_subtitle: 'All-in-one: engineering tools, technical calculations, conversions, and professional toolkit.',
        inst_desc: 'Instruments is the ultimate toolkit designed for engineers, technicians, and hobbyists who need precise and immediate calculations directly on their Android device. Perfect for automation professionals, electricians, and plumbers, the app offers a complete suite of ready-to-use tools:',
        inst_feat1_title: 'Professional Electrical Calculations',
        inst_feat1_desc: 'Electrical line calculation, cable sizing, and voltage drop.',
        inst_feat2_title: 'Instrumentation and Signals',
        inst_feat2_desc: '4-20mA signal converter with scale display.',
        inst_feat3_title: 'Piping Calculator',
        inst_feat3_desc: 'Pipe sizing and hydraulic calculations for fluids.',
        inst_feat4_title: 'Resistor Color Code',
        inst_feat4_desc: 'Identify the value of 4 or 5-band resistors in an instant.',
        inst_feat5_title: 'Unit Converters',
        inst_feat5_desc: 'Power, Pressure, Temperature, Real-time Currency.',
        inst_why_title: 'Why choose Instruments?',
        inst_why1: 'Simple and intuitive: Clean interface in Material Design 3.',
        inst_why2: 'Multilingual: Full support for Italian, English, and German.',
        inst_why3: 'Technical Precision: Algorithms tested for professional use.',
        inst_download: 'Download Instruments today and transform your smartphone into a portable calculation lab!',
        inst_btn_play: 'Download on Google Play',
        inst_nav_home: 'Back to Home',
        footer_visits: 'Visits:'
    },
    de: {
        hero_title: '"Sehen wir uns an, wo wir Zeit und Geld verlieren"',
        hero_subtitle: 'Unterstützung für Produktionsunternehmen zur Optimierung bestehender Anlagen und zur Stärkung der Senior-Diagnostik.',
        btn_discover: 'Dienste Entdecken',
        section_industrial_title: 'Anlagenoptimierung & Zuverlässigkeit',
        section_industrial_subtitle: 'Keine reine Technologie, sondern systemische Vision und diagnostische Fähigkeit.',
        card_guasti_title: 'Fehlersuche & Behebung',
        card_guasti_desc: 'Gezielte Eingriffe zur Behebung wiederholter Fehler und zur Vermeidung erneuter Probleme.',
        card_fermi_title: 'Ausfallzeitreduzierung',
        card_fermi_desc: 'Logische Analyse von Prozessen zur Minimierung chronischer Ineffizienzen und Stillstandszeiten.',
        card_rendimento_title: 'Ertragssteigerung',
        card_rendimento_desc: 'Optimierung der Produktionsleistung durch einen analytischen und globalen Ansatz.',
        card_modern_title: 'Modernisierungsunterstützung',
        card_modern_desc: 'Professionelle technische Unterstützung bei der Erneuerung und Modernisierung bestehender Maschinen.',
        card_invest_title: 'Pre-Investment Bewertung',
        card_invest_desc: 'Technische Analyse und Beratung, um sicherzustellen, dass jede neue Investition gezielt und effektiv ist.',
        card_logica_title: 'Logische Analyse',
        card_logica_desc: 'Eingehende Untersuchung von Arbeitsabläufen zur Beseitigung von Engpässen und Verschwendung.',
        quote: '"Ein erfahrener Techniker ist mehr wert als jemand, der nur neuen Code schreibt."',
        quote_desc: 'Unsere Stärke liegt in der Erfahrung und der Fähigkeit, die gesamte Anlage zu sehen, nicht nur die einzelne Komponente.',
        nav_tech: 'Technologie',
        nav_wellness: 'Wellness',
        nav_industrial: 'Industrie',
        tech_title: 'Technologische Lösungen',
        tech_subtitle: 'Von der Industrieautomatisierung bis zur Entwicklung moderner Android-Apps und Websites.',
        wellness_title: 'Reiki & Wohlbefinden',
        wellness_subtitle: 'Lösungen für das menschliche Gleichgewicht und die Energierückgewinnung.',
        footer_rights: 'Alle Rechte vorbehalten.',
        nav_app: 'Instruments App',
        inst_hero_title: 'Instruments Tools',
        inst_hero_subtitle: 'All-in-one: Ingenieurwerkzeuge, technische Berechnungen, Umrechnungen und professionelles Toolkit.',
        inst_desc: 'Instruments ist das ultimative Toolkit für Ingenieure, Techniker und Bastler, die präzise und sofortige Berechnungen direkt auf ihrem Android-Gerät benötigen. Perfekt für Automatisierungsprofis, Elektriker und Klempner, bietet die App eine komplette Suite an einsatzbereiten Werkzeugen:',
        inst_feat1_title: 'Professionelle elektrische Berechnungen',
        inst_feat1_desc: 'Berechnung von Stromleitungen, Kabeldimensionierung und Spannungsabfall.',
        inst_feat2_title: 'Instrumentierung und Signale',
        inst_feat2_desc: '4-20mA Signalwandler mit Skalenanzeige.',
        inst_feat3_title: 'Rohrleitungsrechner',
        inst_feat3_desc: 'Rohrdimensionierung und hydraulische Berechnungen für Flüssigkeiten.',
        inst_feat4_title: 'Widerstandsfarbcode',
        inst_feat4_desc: 'Identifizieren Sie den Wert von 4- oder 5-Band-Widerständen im Handumdrehen.',
        inst_feat5_title: 'Einheitenumrechner',
        inst_feat5_desc: 'Leistung, Druck, Temperatur, Währung in Echtzeit.',
        inst_why_title: 'Warum Instruments wählen?',
        inst_why1: 'Einfach und intuitiv: Saubere Oberfläche im Material Design 3.',
        inst_why2: 'Mehrsprachig: Volle Unterstützung für Italienisch, Englisch und Deutsch.',
        inst_why3: 'Technische Präzision: Algorithmen getestet für den professionellen Einsatz.',
        inst_download: 'Laden Sie Instruments noch heute herunter und verwandeln Sie Ihr Smartphone in ein tragbares Berechnungslabor!',
        inst_btn_play: 'Download bei Google Play',
        inst_nav_home: 'Zurück zur Startseite',
        footer_visits: 'Besuche:'
    }
};
